import type { EventData, EventType } from './event-data';

export const DEFAULT_EVENT_DATA: Record<EventType, Partial<EventData>> = {
  wedding: {
    eventType: 'wedding',
    primaryName: 'Priya',
    secondaryName: 'Rahul',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 2)).toISOString().split('T')[0],
    eventTime: '19:00',
    venueName: 'The Grand Taj Palace',
    venueAddress: 'Diplomatic Enclave, New Delhi',
    message: 'Join us to celebrate our new beginning.',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  birthday: {
    eventType: 'birthday',
    primaryName: 'Aarav',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '18:00',
    venueName: 'Sky Lounge, Bandra',
    venueAddress: 'Mumbai, Maharashtra',
    message: 'Come celebrate with cake, music, and good vibes!',
    familyDetails: 'Hosted by the Sharma Family',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  engagement: {
    eventType: 'engagement',
    primaryName: 'Ananya',
    secondaryName: 'Vikram',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '19:30',
    venueName: 'The Leela Palace',
    venueAddress: 'Chanakyapuri, New Delhi',
    message: 'We said yes! Join us for our ring ceremony.',
    familyDetails: 'Daughter of Mr. & Mrs. Patel',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  'baby-shower': {
    eventType: 'baby-shower',
    primaryName: 'Sarah & James',
    tagline: 'Baby Shower',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '11:00',
    venueName: 'Garden Terrace Cafe',
    venueAddress: 'Koramangala, Bengaluru',
    message: 'Help us shower the parents-to-be with love!',
    familyDetails: 'Registry details shared on RSVP',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  housewarming: {
    eventType: 'housewarming',
    primaryName: 'The Mehta Family',
    tagline: 'Griha Pravesh',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '10:00',
    venueName: 'Our New Home',
    venueAddress: 'Sector 62, Noida, UP',
    message: 'Bless our new home with your presence.',
    familyDetails: 'Flat 402, Tower B, Green Valley Apartments',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  anniversary: {
    eventType: 'anniversary',
    primaryName: 'Ravi',
    secondaryName: 'Meera',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '19:00',
    venueName: 'The Oberoi',
    venueAddress: 'Gurgaon, Haryana',
    message: 'Join us as we celebrate decades of love.',
    familyDetails: 'Celebrating 25 Years Together',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  farewell: {
    eventType: 'farewell',
    primaryName: 'Aditi',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '18:30',
    venueName: 'The Social',
    venueAddress: 'Indiranagar, Bengaluru',
    message: 'Wishing you all the best in your new journey!',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  conference: {
    eventType: 'conference',
    primaryName: 'Global AI Summit 2026',
    secondaryName: 'TechCorp',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 3)).toISOString().split('T')[0],
    eventTime: '09:00',
    venueName: 'Convention Centre Hall A',
    venueAddress: 'Hyderabad, Telangana',
    message: 'Network, learn, and grow with industry leaders.',
    agenda: '9 AM: Keynote\n11 AM: Panels\n2 PM: Workshops',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  corporate: {
    eventType: 'corporate',
    primaryName: 'Annual Tech Summit 2026',
    secondaryName: 'Acme Corp',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 2)).toISOString().split('T')[0],
    eventTime: '09:00',
    venueName: 'Convention Centre Hall A',
    venueAddress: 'Hyderabad, Telangana',
    message: 'Network, learn, and grow with industry leaders.',
    agenda: 'Business casual · Keynote at 10 AM',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  'product-launch': {
    eventType: 'product-launch',
    primaryName: 'InviteHub 2.0 Launch',
    secondaryName: 'InviteHub',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '10:00',
    venueName: 'Virtual',
    isVirtual: true,
    virtualLink: 'https://youtube.com/invitehub',
    message: 'Join us as we unveil the future of event management.',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  retirement: {
    eventType: 'retirement',
    primaryName: 'Mr. Sharma',
    secondaryName: 'Acme Corp',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '17:00',
    venueName: 'The Grand Hall',
    venueAddress: 'Mumbai, India',
    message: 'Celebrating 30 years of excellence. Join us in wishing him a happy retirement.',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  webinar: {
    eventType: 'webinar',
    primaryName: 'Mastering Next.js',
    secondaryName: 'Vercel',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '14:00',
    venueName: 'Virtual',
    isVirtual: true,
    virtualLink: 'https://zoom.us/webinar',
    message: 'Learn the ins and outs of Next.js 16.',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  networking: {
    eventType: 'networking',
    primaryName: 'Founders Mixer',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '19:00',
    venueName: 'WeWork',
    venueAddress: 'Bengaluru, India',
    message: 'Connect with fellow founders and investors.',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  townhall: {
    eventType: 'townhall',
    primaryName: 'Q3 All Hands',
    secondaryName: 'Acme Corp',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '10:00',
    venueName: 'Virtual',
    isVirtual: true,
    virtualLink: 'https://zoom.us/townhall',
    message: 'Updates on Q3 performance and Q4 goals.',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  workshop: {
    eventType: 'workshop',
    primaryName: 'Design Systems 101',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '10:00',
    venueName: 'Design Studio',
    venueAddress: 'Pune, India',
    message: 'A hands-on workshop on building scalable design systems.',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  school: {
    eventType: 'school',
    primaryName: 'Annual Day 2026',
    secondaryName: 'Delhi Public School',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '17:00',
    venueName: 'School Auditorium',
    venueAddress: 'New Delhi, India',
    message: 'Join us for a spectacular evening of performances by our students.',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
  community: {
    eventType: 'community',
    primaryName: 'Beach Cleanup Drive',
    eventDate: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString().split('T')[0],
    eventTime: '07:00',
    venueName: 'Juhu Beach',
    venueAddress: 'Mumbai, India',
    message: 'Let us come together to keep our beaches clean.',
    rsvpEnabled: true,
    calendarEnabled: true,
    mapEnabled: true,
  },
};

export function getDefaultEventData(eventType: EventType = 'wedding'): Partial<EventData> {
  return { ...DEFAULT_EVENT_DATA[eventType], eventType, timezone: 'Asia/Kolkata' };
}
