import type { Template } from './types';

export const TEMPLATE_CATEGORIES = [
  { id: 'wedding', label: 'Wedding', description: 'Classic wedding designs' },
  { id: 'royal', label: 'Royal', description: 'Luxurious royal designs' },
  { id: 'floral', label: 'Floral', description: 'Floral and botanical themes' },
  { id: 'traditional-indian', label: 'Traditional Indian', description: 'Traditional Indian wedding styles' },
  { id: 'modern', label: 'Modern', description: 'Contemporary and minimalist designs' },
];

export const TEMPLATES: Template[] = [
  {
    id: 'elegant-gold-001',
    name: 'Elegant Gold',
    description: 'Sophisticated golden theme with elegant fonts and graceful layouts. Perfect for formal celebrations.',
    category: 'wedding',
    previewUrl: '/Elegant gold wedding invitation design.png',
    thumbnailUrl: '/Elegant gold wedding invitation design.png',
    tier: 'free',
    tags: ['gold', 'elegant', 'formal', 'classic'],
    features: ['Gold accents', 'Elegant typography', 'High-res ready', 'Customizable colors'],
    isPopular: true,
  },
  {
    id: 'modern-geometric-002',
    name: 'Modern Geometric',
    description: 'Clean geometric patterns with modern minimalist design. Ideal for contemporary couples.',
    category: 'modern',
    previewUrl: '/Modern geometric wedding invitation design.png',
    thumbnailUrl: '/Modern geometric wedding invitation design.png',
    tier: 'free',
    tags: ['geometric', 'modern', 'minimalist', 'clean'],
    features: ['Bold geometry', 'Minimalist layout', 'Mobile optimized', 'Easy to customize'],
    isPopular: true,
  },
  {
    id: 'romantic-vintage-003',
    name: 'Romantic Vintage',
    description: 'Vintage-inspired design with romantic elements. Perfect for couples who love classic aesthetics.',
    category: 'wedding',
    previewUrl: '/Romantic vintage wedding invitation design.png',
    thumbnailUrl: '/Romantic vintage wedding invitation design.png',
    tier: 'free',
    tags: ['vintage', 'romantic', 'classic', 'antique'],
    features: ['Vintage patterns', 'Romantic fonts', 'Photo-friendly', 'Premium feel'],
  },
  {
    id: 'traditional-indian-004',
    name: 'Traditional Indian',
    description: 'Authentic Indian wedding design with traditional motifs and colors. Celebrates Indian heritage.',
    category: 'traditional-indian',
    previewUrl: '/Traditional Indian wedding invitation design.png',
    thumbnailUrl: '/Traditional Indian wedding invitation design.png',
    tier: 'free',
    tags: ['traditional', 'indian', 'cultural', 'motifs'],
    features: ['Traditional motifs', 'Indian color palette', 'Marigold elements', 'Bilingual ready'],
    isPopular: true,
  },
  {
    id: 'royal-purple-005',
    name: 'Royal Purple',
    description: 'Luxurious purple and gold royal design. Perfect for grand celebrations and royal affairs.',
    category: 'royal',
    previewUrl: '/images/templates/royal-purple.png',
    thumbnailUrl: '/images/templates/royal-purple-thumb.png',
    tier: 'premium',
    tags: ['royal', 'purple', 'luxurious', 'grand'],
    features: ['Royal purple gradient', 'Gold embellishments', 'Premium fonts', 'HD resolution'],
    isNew: true,
  },
  {
    id: 'floral-bloom-006',
    name: 'Floral Bloom',
    description: 'Beautiful floral design with watercolor flowers. Perfect for spring and garden weddings.',
    category: 'floral',
    previewUrl: '/images/templates/floral-bloom.png',
    thumbnailUrl: '/images/templates/floral-bloom-thumb.png',
    tier: 'premium',
    tags: ['floral', 'watercolor', 'flowers', 'garden'],
    features: ['Watercolor flowers', 'Soft colors', 'Botanical elements', 'Elegant spacing'],
    isNew: true,
  },
  {
    id: 'modern-blush-007',
    name: 'Modern Blush',
    description: 'Contemporary blush pink and white design. Trendy and Instagram-ready for modern couples.',
    category: 'modern',
    previewUrl: '/images/templates/modern-blush.png',
    thumbnailUrl: '/images/templates/modern-blush-thumb.png',
    tier: 'premium',
    tags: ['modern', 'blush', 'minimalist', 'trendy'],
    features: ['Blush pink palette', 'Modern spacing', 'Social media optimized', 'High-res'],
  },
  {
    id: 'traditional-maroon-008',
    name: 'Traditional Maroon',
    description: 'Rich maroon and gold traditional design. Timeless choice for Indian wedding celebrations.',
    category: 'traditional-indian',
    previewUrl: '/images/templates/traditional-maroon.png',
    thumbnailUrl: '/images/templates/traditional-maroon-thumb.png',
    tier: 'premium',
    tags: ['traditional', 'maroon', 'indian', 'cultural'],
    features: ['Rich maroon base', 'Gold accents', 'Cultural motifs', 'Traditional fonts'],
  },
  {
    id: 'luxury-black-009',
    name: 'Luxury Black',
    description: 'Sleek black and white luxury design. Perfect for sophisticated and formal celebrations.',
    category: 'royal',
    previewUrl: '/images/templates/luxury-black.png',
    thumbnailUrl: '/images/templates/luxury-black-thumb.png',
    tier: 'premium-plus',
    tags: ['luxury', 'black', 'formal', 'sophisticated'],
    features: ['Premium black', 'Silver accents', 'Modern typography', 'Envelope design included'],
    isPopular: true,
  },
  {
    id: 'pastel-garden-010',
    name: 'Pastel Garden',
    description: 'Soft pastel flowers with garden theme. Perfect for spring and outdoor celebrations.',
    category: 'floral',
    previewUrl: '/images/templates/pastel-garden.png',
    thumbnailUrl: '/images/templates/pastel-garden-thumb.png',
    tier: 'premium-plus',
    tags: ['floral', 'pastel', 'garden', 'spring'],
    features: ['Pastel palette', 'Garden elements', 'Botanical art', 'Envelope design included'],
  },

  // ── Wedding ──────────────────────────────────────────────────────────────
  {
    id: 'white-elegance-011',
    name: 'White Elegance',
    description: 'Pristine cream and gold design with monogram circle and curved arch accents. Timeless sophistication.',
    category: 'wedding',
    previewUrl: '/images/templates/white-elegance.png',
    thumbnailUrl: '/images/templates/white-elegance.png',
    tier: 'free',
    tags: ['white', 'elegant', 'cream', 'monogram', 'arch'],
    features: ['Monogram circle', 'Cream palette', 'Arch accents', 'Script typography'],
    isNew: true,
  },
  {
    id: 'botanical-garden-012',
    name: 'Botanical Garden',
    description: 'Lush sage-green botanical theme with hand-drawn leaf sprigs. Perfect for garden and outdoor weddings.',
    category: 'wedding',
    previewUrl: '/images/templates/botanical-garden.png',
    thumbnailUrl: '/images/templates/botanical-garden.png',
    tier: 'free',
    tags: ['botanical', 'green', 'garden', 'leaves', 'nature'],
    features: ['Sage green palette', 'Botanical sprigs', 'EB Garamond serif', 'Nature-inspired'],
    isNew: true,
  },
  {
    id: 'midnight-romance-013',
    name: 'Midnight Romance',
    description: 'Dramatic dark navy with twinkling stars, glowing moon, and shimmering gold script. Perfect for evening soirées.',
    category: 'wedding',
    previewUrl: '/images/templates/midnight-romance.png',
    thumbnailUrl: '/images/templates/midnight-romance.png',
    tier: 'premium',
    tags: ['dark', 'navy', 'stars', 'gold', 'night', 'romantic'],
    features: ['Star particle animation', 'Gold shimmer text', 'Glowing moon', 'Dark luxury'],
    isPopular: true,
    isNew: true,
  },

  // ── Modern ───────────────────────────────────────────────────────────────
  {
    id: 'arc-minimalist-014',
    name: 'Arc Minimalist',
    description: 'Bold terracotta arch with left-aligned oversized names. Clean, editorial, and completely unmissable.',
    category: 'modern',
    previewUrl: '/images/templates/arc-minimalist.png',
    thumbnailUrl: '/images/templates/arc-minimalist.png',
    tier: 'free',
    tags: ['modern', 'arc', 'terracotta', 'bold', 'editorial'],
    features: ['Arc background shape', 'Oversized names', 'White card details', 'Space Grotesk'],
    isNew: true,
  },
  {
    id: 'ink-blush-015',
    name: 'Ink Blush',
    description: 'Soft blush and lavender watercolour blobs with DM Serif italic script. Trendy, feminine, Instagram-ready.',
    category: 'modern',
    previewUrl: '/images/templates/ink-blush.png',
    thumbnailUrl: '/images/templates/ink-blush.png',
    tier: 'premium',
    tags: ['blush', 'lavender', 'watercolour', 'soft', 'feminine'],
    features: ['Watercolour blobs', 'Clip-path reveal animation', '3-column layout', 'DM Serif Display'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'neo-brutal-016',
    name: 'Neo Brutalist',
    description: 'Raw, bold neo-brutalist design with stark black borders, massive Syne typography, and hard-edge aesthetic.',
    category: 'modern',
    previewUrl: '/images/templates/neo-brutal.png',
    thumbnailUrl: '/images/templates/neo-brutal.png',
    tier: 'premium-plus',
    tags: ['brutalist', 'bold', 'black', 'modern', 'graphic'],
    features: ['Neo-brutalist style', 'Syne ExtraBold', 'Offset shadow frame', 'Date badge label'],
    isNew: true,
  },

  // ── Traditional ──────────────────────────────────────────────────────────
  {
    id: 'golden-paisley-017',
    name: 'Golden Paisley',
    description: 'Deep brown and gold with SVG paisley corner motifs and Devanagari mangalacharan. Rich Indian heritage.',
    category: 'traditional-indian',
    previewUrl: '/images/templates/golden-paisley.png',
    thumbnailUrl: '/images/templates/golden-paisley.png',
    tier: 'free',
    tags: ['paisley', 'gold', 'brown', 'devanagari', 'traditional'],
    features: ['Paisley motifs', 'Devanagari script', 'Gold gradient bands', 'Heritage palette'],
    isNew: true,
  },
  {
    id: 'marigold-fiesta-018',
    name: 'Marigold Fiesta',
    description: 'Saffron, maroon, and marigold with rangoli diamond strips and Yatra One Devanagari headers. Vibrant festival energy.',
    category: 'traditional-indian',
    previewUrl: '/images/templates/marigold-fiesta.png',
    thumbnailUrl: '/images/templates/marigold-fiesta.png',
    tier: 'free',
    tags: ['marigold', 'saffron', 'rangoli', 'maroon', 'festive'],
    features: ['Rangoli SVG strip', 'Chevron bands', 'Yatra One font', 'Festival colours'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'kerala-temple-019',
    name: 'Kerala Temple',
    description: 'Warm golden-saffron with SVG temple arch bands, mandala corner ornaments, and Noto Serif italic script.',
    category: 'traditional-indian',
    previewUrl: '/images/templates/kerala-temple.png',
    thumbnailUrl: '/images/templates/kerala-temple.png',
    tier: 'premium',
    tags: ['kerala', 'temple', 'mandala', 'south-indian', 'arch'],
    features: ['Temple arch bands', 'Mandala corners', 'Noto Serif', 'Saffron palette'],
    isNew: true,
  },
  {
    id: 'modern-floral-020',
    name: 'Modern Floral Geometric',
    description: 'Bold geometric corner triangles in coral, teal & purple with gold floral line art. A modern-meets-traditional fusion.',
    category: 'modern',
    previewUrl: '/images/templates/modern-floral.png',
    thumbnailUrl: '/images/templates/modern-floral.png',
    tier: 'premium',
    tags: ['modern', 'floral', 'geometric', 'colorful', 'fusion'],
    features: ['Bold corner geometry', 'Floral SVG art', 'Diamond photo frame', 'Great Vibes script'],
    isNew: true,
    isPopular: true,
  },

  // ── Additional Event Types (Phase 9) ─────────────────────────────────────
  {
    id: 'birthday-confetti-021',
    name: 'Birthday Confetti',
    description: 'Vibrant pink celebration design with festive emoji accents. Perfect for birthday parties of all ages.',
    eventType: 'birthday',
    category: 'modern',
    previewUrl: '/images/templates/birthday-confetti.png',
    thumbnailUrl: '/images/templates/birthday-confetti.png',
    tier: 'free',
    tags: ['birthday', 'party', 'confetti', 'pink', 'celebration'],
    features: ['Festive pink palette', 'Age/tagline display', 'Photo upload', 'Mobile optimized'],
    isNew: true,
  },
  {
    id: 'engagement-rings-022',
    name: 'Engagement Rings',
    description: 'Elegant purple engagement design with ring motif. Ideal for ring ceremonies and engagement parties.',
    eventType: 'engagement',
    category: 'wedding',
    previewUrl: '/images/templates/engagement-rings.png',
    thumbnailUrl: '/images/templates/engagement-rings.png',
    tier: 'free',
    tags: ['engagement', 'rings', 'purple', 'couple', 'ceremony'],
    features: ['Ring ceremony styling', 'Couple names', 'Family details field', 'Elegant typography'],
    isNew: true,
  },
  {
    id: 'baby-shower-cloud-023',
    name: 'Baby Shower Cloud',
    description: 'Soft sky-blue baby shower design with gentle cloud aesthetic. Perfect for parents-to-be.',
    eventType: 'baby-shower',
    category: 'floral',
    previewUrl: '/images/templates/baby-shower-cloud.png',
    thumbnailUrl: '/images/templates/baby-shower-cloud.png',
    tier: 'free',
    tags: ['baby shower', 'blue', 'cloud', 'parents', 'celebration'],
    features: ['Soft blue palette', 'Parent names', 'Registry note field', 'Gentle typography'],
    isNew: true,
  },
  {
    id: 'housewarming-home-024',
    name: 'Housewarming Home',
    description: 'Fresh green housewarming design for griha pravesh and new home celebrations.',
    eventType: 'housewarming',
    category: 'modern',
    previewUrl: '/images/templates/housewarming-home.png',
    thumbnailUrl: '/images/templates/housewarming-home.png',
    tier: 'free',
    tags: ['housewarming', 'griha pravesh', 'home', 'green', 'new home'],
    features: ['Griha pravesh ready', 'Host names', 'Address note field', 'Fresh green theme'],
    isNew: true,
  },
  {
    id: 'anniversary-hearts-025',
    name: 'Anniversary Hearts',
    description: 'Romantic red anniversary design celebrating years of love and togetherness.',
    eventType: 'anniversary',
    category: 'wedding',
    previewUrl: '/images/templates/anniversary-hearts.png',
    thumbnailUrl: '/images/templates/anniversary-hearts.png',
    tier: 'free',
    tags: ['anniversary', 'hearts', 'red', 'milestone', 'celebration'],
    features: ['Milestone display', 'Couple names', 'Years together field', 'Romantic styling'],
    isNew: true,
  },
  {
    id: 'corporate-minimal-026',
    name: 'Corporate Minimal',
    description: 'Clean professional design for conferences, summits, and corporate gatherings.',
    eventType: 'corporate',
    category: 'modern',
    previewUrl: '/images/templates/corporate-minimal.png',
    thumbnailUrl: '/images/templates/corporate-minimal.png',
    tier: 'free',
    tags: ['corporate', 'business', 'conference', 'professional', 'minimal'],
    features: ['Professional layout', 'Event title & company', 'Agenda note field', 'Logo upload'],
    isNew: true,
  },

  // ── Birthday (Designer Collection) ───────────────────────────────────────
  {
    id: 'birthday-neon-glow-027',
    name: 'Neon Glow',
    description: 'Bold dark canvas with vibrant neon gradients and confetti accents. Perfect for teens and young adult parties.',
    eventType: 'birthday',
    category: 'modern',
    previewUrl: '/images/templates/birthday-neon-glow.png',
    thumbnailUrl: '/images/templates/birthday-neon-glow.png',
    tier: 'premium',
    tags: ['birthday', 'neon', 'dark', 'modern', 'party'],
    features: ['Neon gradient typography', 'Animated confetti dots', 'Dark party aesthetic', 'Photo frame'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'birthday-balloon-burst-028',
    name: 'Balloon Burst',
    description: 'Cheerful pastel design with illustrated floating balloons. Ideal for kids birthday celebrations.',
    eventType: 'birthday',
    category: 'floral',
    previewUrl: '/images/templates/birthday-balloon-burst.png',
    thumbnailUrl: '/images/templates/birthday-balloon-burst.png',
    tier: 'free',
    tags: ['birthday', 'balloons', 'kids', 'pastel', 'fun'],
    features: ['SVG balloon illustrations', 'Warm pastel palette', 'Playful Fredoka typography', 'Kid-friendly'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'birthday-gold-glam-029',
    name: 'Gold Glam',
    description: 'Luxurious black and gold design with ornamental frame. Sophisticated choice for milestone adult birthdays.',
    eventType: 'birthday',
    category: 'royal',
    previewUrl: '/images/templates/birthday-gold-glam.png',
    thumbnailUrl: '/images/templates/birthday-gold-glam.png',
    tier: 'premium',
    tags: ['birthday', 'gold', 'luxury', 'adult', 'glam'],
    features: ['Gold corner ornaments', 'Cormorant serif typography', 'Milestone celebration ready', 'Premium dark theme'],
    isNew: true,
  },
  {
    id: 'birthday-garden-party-030',
    name: 'Garden Party',
    description: 'Serene sage-green botanical design with hand-drawn leaf sprigs. Perfect for outdoor garden birthdays.',
    eventType: 'birthday',
    category: 'floral',
    previewUrl: '/images/templates/birthday-garden-party.png',
    thumbnailUrl: '/images/templates/birthday-garden-party.png',
    tier: 'free',
    tags: ['birthday', 'garden', 'botanical', 'green', 'outdoor'],
    features: ['Botanical leaf SVG art', 'Sage green palette', 'Glass-morphism card', 'Outdoor party feel'],
    isNew: true,
  },
  {
    id: 'birthday-retro-disco-031',
    name: 'Retro Disco',
    description: 'Vibrant 70s-inspired disco design with warm sunset gradient and bold retro typography.',
    eventType: 'birthday',
    category: 'modern',
    previewUrl: '/images/templates/birthday-retro-disco.png',
    thumbnailUrl: '/images/templates/birthday-retro-disco.png',
    tier: 'premium-plus',
    tags: ['birthday', 'disco', 'retro', '70s', 'party'],
    features: ['Retro sun burst animation', 'Bold Righteous display font', 'Sunset gradient background', 'Unique tilted photo frame'],
    isNew: true,
  },

  // ── Baby Shower (Designer Collection) ────────────────────────────────────
  {
    id: 'baby-shower-safari-032',
    name: 'Safari Adventure',
    description: 'Warm neutral safari theme with subtle animal illustrations. Gender-neutral and adventure-ready.',
    eventType: 'baby-shower',
    category: 'modern',
    previewUrl: '/images/templates/baby-shower-safari.png',
    thumbnailUrl: '/images/templates/baby-shower-safari.png',
    tier: 'free',
    tags: ['baby shower', 'safari', 'neutral', 'animals', 'warm'],
    features: ['Safari animal SVG art', 'Gender-neutral palette', 'Savannah horizon', 'Playful Baloo typography'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'baby-shower-pastel-rainbow-033',
    name: 'Pastel Rainbow',
    description: 'Soft animated rainbow arches in dreamy pastels. A joyful, inclusive baby shower design.',
    eventType: 'baby-shower',
    category: 'floral',
    previewUrl: '/images/templates/baby-shower-pastel-rainbow.png',
    thumbnailUrl: '/images/templates/baby-shower-pastel-rainbow.png',
    tier: 'premium',
    tags: ['baby shower', 'rainbow', 'pastel', 'colorful', 'joyful'],
    features: ['Animated rainbow arches', '6-color pastel palette', 'Comfortaa rounded typography', 'Inclusive design'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'baby-shower-moon-stars-034',
    name: 'Moon & Stars',
    description: 'Dreamy midnight navy with glowing moon and twinkling stars. Elegant gender-neutral nursery aesthetic.',
    eventType: 'baby-shower',
    category: 'modern',
    previewUrl: '/images/templates/baby-shower-moon-stars.png',
    thumbnailUrl: '/images/templates/baby-shower-moon-stars.png',
    tier: 'premium',
    tags: ['baby shower', 'moon', 'stars', 'night', 'dreamy'],
    features: ['Animated twinkling stars', 'Glowing moon illustration', 'Cormorant Infant serif', 'Dark luxury theme'],
    isNew: true,
  },
  {
    id: 'baby-shower-floral-pink-035',
    name: 'Floral Bloom Pink',
    description: 'Romantic blush watercolor florals with elegant script typography. A classic baby shower favourite.',
    eventType: 'baby-shower',
    category: 'floral',
    previewUrl: '/images/templates/baby-shower-floral-pink.png',
    thumbnailUrl: '/images/templates/baby-shower-floral-pink.png',
    tier: 'free',
    tags: ['baby shower', 'floral', 'pink', 'watercolor', 'romantic'],
    features: ['Watercolor floral corners', 'Great Vibes script', 'Blush pink gradient', 'Elegant feminine style'],
    isNew: true,
  },
  {
    id: 'baby-shower-minimal-nursery-036',
    name: 'Minimal Nursery',
    description: 'Clean Scandinavian nursery design with soft arch and neutral tones. Modern and timeless.',
    eventType: 'baby-shower',
    category: 'modern',
    previewUrl: '/images/templates/baby-shower-minimal-nursery.png',
    thumbnailUrl: '/images/templates/baby-shower-minimal-nursery.png',
    tier: 'premium-plus',
    tags: ['baby shower', 'minimal', 'scandinavian', 'neutral', 'modern'],
    features: ['Scandinavian arch shape', 'Outfit modern typography', 'Neutral nursery palette', 'Dot pattern detail'],
    isNew: true,
  },

  // ── Corporate (Professional Collection) ────────────────────────────────────
  {
    id: 'corporate-executive-navy-037',
    name: 'Executive Navy',
    description: 'Boardroom-ready navy and gold design with blueprint grid. Ideal for galas, launches, and executive events.',
    eventType: 'corporate',
    category: 'royal',
    previewUrl: '/images/templates/corporate-executive-navy.png',
    thumbnailUrl: '/images/templates/corporate-executive-navy.png',
    tier: 'premium',
    tags: ['corporate', 'executive', 'navy', 'gold', 'formal'],
    features: ['Navy & gold palette', 'Company monogram block', 'Agenda detail panel', 'Libre Baskerville serif'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'corporate-tech-summit-038',
    name: 'Tech Summit',
    description: 'Sleek dark tech conference design with cyan circuit accents. Built for summits, hackathons, and product launches.',
    eventType: 'corporate',
    category: 'modern',
    previewUrl: '/images/templates/corporate-tech-summit.png',
    thumbnailUrl: '/images/templates/corporate-tech-summit.png',
    tier: 'premium',
    tags: ['corporate', 'tech', 'summit', 'conference', 'startup'],
    features: ['Circuit line grid', 'Cyan accent glow', 'Space Grotesk display', 'Logo banner slot'],
    isNew: true,
    isPopular: true,
  },

  // ── Photo-Centric Background Templates (Phase 10) ─────────────────────────
  {
    id: 'birthday-magazine-cover-039',
    name: 'Magazine Cover',
    description: 'Editorial Vogue/GQ style design where your photo is the full background. Striking typography with a sleek glassmorphism detail panel.',
    eventType: 'birthday',
    category: 'modern',
    previewUrl: '/images/templates/birthday-magazine-cover.png',
    thumbnailUrl: '/images/templates/birthday-magazine-cover.png',
    tier: 'premium-plus',
    tags: ['birthday', 'magazine', 'editorial', 'photo', 'glassmorphism'],
    features: ['Full-bleed background photo', 'Editorial typography', 'Glassmorphism panel', 'Fashion aesthetic'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'birthday-vintage-film-040',
    name: 'Vintage Film',
    description: 'Nostalgic retro film aesthetic with your full photo background, glowing typography, and Polaroid accents.',
    eventType: 'birthday',
    category: 'floral',
    previewUrl: '/images/templates/birthday-vintage-film.png',
    thumbnailUrl: '/images/templates/birthday-vintage-film.png',
    tier: 'premium',
    tags: ['birthday', 'vintage', 'retro', 'film', 'polaroid', 'photo'],
    features: ['Full-bleed background photo', 'Vintage film grain', 'Glowing retro text', 'Polaroid frames'],
    isNew: true,
  },
  {
    id: 'corporate-executive-glass-041',
    name: 'Executive Glass',
    description: 'Ultra-modern business summit design. Uses your team or building photo as the background with a pristine frosted glass agenda panel.',
    eventType: 'corporate',
    category: 'modern',
    previewUrl: '/images/templates/corporate-executive-glass.png',
    thumbnailUrl: '/images/templates/corporate-executive-glass.png',
    tier: 'premium-plus',
    tags: ['corporate', 'tech', 'glassmorphism', 'business', 'photo'],
    features: ['Full-bleed background photo', 'Frosted glass UI', 'Minimalist typography', 'Tech summit ready'],
    isNew: true,
  },
  {
    id: 'corporate-cinematic-gala-042',
    name: 'Cinematic Gala',
    description: 'High-end award ceremony aesthetic. Your photo is draped in a dramatic dark gradient with luxurious gold text overlaid.',
    eventType: 'corporate',
    category: 'royal',
    previewUrl: '/images/templates/corporate-cinematic-gala.png',
    thumbnailUrl: '/images/templates/corporate-cinematic-gala.png',
    tier: 'premium-plus',
    tags: ['corporate', 'gala', 'awards', 'cinematic', 'gold', 'photo'],
    features: ['Full-bleed background photo', 'Cinematic dark gradient', 'Gold/Silver text', 'Premium formal style'],
    isNew: true,
    isPopular: true,
  },
];


export const TEMPLATE_TIERS = {
  free: {
    label: 'Free',
    description: 'Watermarked downloads, shareable link',
    price: 0,
  },
  premium: {
    label: 'Premium',
    description: 'HD PNG, no watermark',
    price: 49,
  },
  'premium-plus': {
    label: 'Premium Plus',
    description: 'HD PNG, PDF, Envelope Design, no watermark',
    price: 99,
  },
};
