import type { Template } from './types';

export const TEMPLATE_CATEGORIES = [
  { id: 'wedding', label: 'Wedding', description: 'Classic wedding designs' },
  { id: 'royal', label: 'Royal', description: 'Luxurious royal designs' },
  { id: 'floral', label: 'Floral', description: 'Floral and botanical themes' },
  { id: 'traditional-indian', label: 'Traditional Indian', description: 'Traditional Indian wedding styles' },
  { id: 'modern', label: 'Modern', description: 'Contemporary and minimalist designs' },
];

export const TEMPLATES: Template[] = [
  {
    id: 'elegant-gold-001',
    name: 'Elegant Gold',
    description: 'Sophisticated golden theme with elegant fonts and graceful layouts. Perfect for formal celebrations.',
    category: 'wedding',
    previewUrl: '/Elegant gold wedding invitation design.png',
    thumbnailUrl: '/Elegant gold wedding invitation design.png',
    tier: 'free',
    tags: ['gold', 'elegant', 'formal', 'classic'],
    features: ['Gold accents', 'Elegant typography', 'High-res ready', 'Customizable colors'],
    isPopular: true,
  },
  {
    id: 'modern-geometric-002',
    name: 'Modern Geometric',
    description: 'Clean geometric patterns with modern minimalist design. Ideal for contemporary couples.',
    category: 'modern',
    previewUrl: '/Modern geometric wedding invitation design.png',
    thumbnailUrl: '/Modern geometric wedding invitation design.png',
    tier: 'free',
    tags: ['geometric', 'modern', 'minimalist', 'clean'],
    features: ['Bold geometry', 'Minimalist layout', 'Mobile optimized', 'Easy to customize'],
    isPopular: true,
  },
  {
    id: 'romantic-vintage-003',
    name: 'Romantic Vintage',
    description: 'Vintage-inspired design with romantic elements. Perfect for couples who love classic aesthetics.',
    category: 'wedding',
    previewUrl: '/Romantic vintage wedding invitation design.png',
    thumbnailUrl: '/Romantic vintage wedding invitation design.png',
    tier: 'free',
    tags: ['vintage', 'romantic', 'classic', 'antique'],
    features: ['Vintage patterns', 'Romantic fonts', 'Photo-friendly', 'Premium feel'],
  },
  {
    id: 'traditional-indian-004',
    name: 'Traditional Indian',
    description: 'Authentic Indian wedding design with traditional motifs and colors. Celebrates Indian heritage.',
    category: 'traditional-indian',
    previewUrl: '/Traditional Indian wedding invitation design.png',
    thumbnailUrl: '/Traditional Indian wedding invitation design.png',
    tier: 'free',
    tags: ['traditional', 'indian', 'cultural', 'motifs'],
    features: ['Traditional motifs', 'Indian color palette', 'Marigold elements', 'Bilingual ready'],
    isPopular: true,
  },
  {
    id: 'royal-purple-005',
    name: 'Royal Purple',
    description: 'Luxurious purple and gold royal design. Perfect for grand celebrations and royal affairs.',
    category: 'royal',
    previewUrl: '/images/templates/royal-purple.png',
    thumbnailUrl: '/images/templates/royal-purple-thumb.png',
    tier: 'premium',
    tags: ['royal', 'purple', 'luxurious', 'grand'],
    features: ['Royal purple gradient', 'Gold embellishments', 'Premium fonts', 'HD resolution'],
    isNew: true,
  },
  {
    id: 'floral-bloom-006',
    name: 'Floral Bloom',
    description: 'Beautiful floral design with watercolor flowers. Perfect for spring and garden weddings.',
    category: 'floral',
    previewUrl: '/images/templates/floral-bloom.png',
    thumbnailUrl: '/images/templates/floral-bloom-thumb.png',
    tier: 'premium',
    tags: ['floral', 'watercolor', 'flowers', 'garden'],
    features: ['Watercolor flowers', 'Soft colors', 'Botanical elements', 'Elegant spacing'],
    isNew: true,
  },
  {
    id: 'modern-blush-007',
    name: 'Modern Blush',
    description: 'Contemporary blush pink and white design. Trendy and Instagram-ready for modern couples.',
    category: 'modern',
    previewUrl: '/images/templates/modern-blush.png',
    thumbnailUrl: '/images/templates/modern-blush-thumb.png',
    tier: 'premium',
    tags: ['modern', 'blush', 'minimalist', 'trendy'],
    features: ['Blush pink palette', 'Modern spacing', 'Social media optimized', 'High-res'],
  },
  {
    id: 'traditional-maroon-008',
    name: 'Traditional Maroon',
    description: 'Rich maroon and gold traditional design. Timeless choice for Indian wedding celebrations.',
    category: 'traditional-indian',
    previewUrl: '/images/templates/traditional-maroon.png',
    thumbnailUrl: '/images/templates/traditional-maroon-thumb.png',
    tier: 'premium',
    tags: ['traditional', 'maroon', 'indian', 'cultural'],
    features: ['Rich maroon base', 'Gold accents', 'Cultural motifs', 'Traditional fonts'],
  },
  {
    id: 'luxury-black-009',
    name: 'Luxury Black',
    description: 'Sleek black and white luxury design. Perfect for sophisticated and formal celebrations.',
    category: 'royal',
    previewUrl: '/images/templates/luxury-black.png',
    thumbnailUrl: '/images/templates/luxury-black-thumb.png',
    tier: 'premium-plus',
    tags: ['luxury', 'black', 'formal', 'sophisticated'],
    features: ['Premium black', 'Silver accents', 'Modern typography', 'Envelope design included'],
    isPopular: true,
  },
  {
    id: 'pastel-garden-010',
    name: 'Pastel Garden',
    description: 'Soft pastel flowers with garden theme. Perfect for spring and outdoor celebrations.',
    category: 'floral',
    previewUrl: '/images/templates/pastel-garden.png',
    thumbnailUrl: '/images/templates/pastel-garden-thumb.png',
    tier: 'premium-plus',
    tags: ['floral', 'pastel', 'garden', 'spring'],
    features: ['Pastel palette', 'Garden elements', 'Botanical art', 'Envelope design included'],
  },

  // ── Wedding ──────────────────────────────────────────────────────────────
  {
    id: 'white-elegance-011',
    name: 'White Elegance',
    description: 'Pristine cream and gold design with monogram circle and curved arch accents. Timeless sophistication.',
    category: 'wedding',
    previewUrl: '/images/templates/white-elegance.png',
    thumbnailUrl: '/images/templates/white-elegance.png',
    tier: 'free',
    tags: ['white', 'elegant', 'cream', 'monogram', 'arch'],
    features: ['Monogram circle', 'Cream palette', 'Arch accents', 'Script typography'],
    isNew: true,
  },
  {
    id: 'botanical-garden-012',
    name: 'Botanical Garden',
    description: 'Lush sage-green botanical theme with hand-drawn leaf sprigs. Perfect for garden and outdoor weddings.',
    category: 'wedding',
    previewUrl: '/images/templates/botanical-garden.png',
    thumbnailUrl: '/images/templates/botanical-garden.png',
    tier: 'free',
    tags: ['botanical', 'green', 'garden', 'leaves', 'nature'],
    features: ['Sage green palette', 'Botanical sprigs', 'EB Garamond serif', 'Nature-inspired'],
    isNew: true,
  },
  {
    id: 'midnight-romance-013',
    name: 'Midnight Romance',
    description: 'Dramatic dark navy with twinkling stars, glowing moon, and shimmering gold script. Perfect for evening soirées.',
    category: 'wedding',
    previewUrl: '/images/templates/midnight-romance.png',
    thumbnailUrl: '/images/templates/midnight-romance.png',
    tier: 'premium',
    tags: ['dark', 'navy', 'stars', 'gold', 'night', 'romantic'],
    features: ['Star particle animation', 'Gold shimmer text', 'Glowing moon', 'Dark luxury'],
    isPopular: true,
    isNew: true,
  },

  // ── Modern ───────────────────────────────────────────────────────────────
  {
    id: 'arc-minimalist-014',
    name: 'Arc Minimalist',
    description: 'Bold terracotta arch with left-aligned oversized names. Clean, editorial, and completely unmissable.',
    category: 'modern',
    previewUrl: '/images/templates/arc-minimalist.png',
    thumbnailUrl: '/images/templates/arc-minimalist.png',
    tier: 'free',
    tags: ['modern', 'arc', 'terracotta', 'bold', 'editorial'],
    features: ['Arc background shape', 'Oversized names', 'White card details', 'Space Grotesk'],
    isNew: true,
  },
  {
    id: 'ink-blush-015',
    name: 'Ink Blush',
    description: 'Soft blush and lavender watercolour blobs with DM Serif italic script. Trendy, feminine, Instagram-ready.',
    category: 'modern',
    previewUrl: '/images/templates/ink-blush.png',
    thumbnailUrl: '/images/templates/ink-blush.png',
    tier: 'premium',
    tags: ['blush', 'lavender', 'watercolour', 'soft', 'feminine'],
    features: ['Watercolour blobs', 'Clip-path reveal animation', '3-column layout', 'DM Serif Display'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'neo-brutal-016',
    name: 'Neo Brutalist',
    description: 'Raw, bold neo-brutalist design with stark black borders, massive Syne typography, and hard-edge aesthetic.',
    category: 'modern',
    previewUrl: '/images/templates/neo-brutal.png',
    thumbnailUrl: '/images/templates/neo-brutal.png',
    tier: 'premium-plus',
    tags: ['brutalist', 'bold', 'black', 'modern', 'graphic'],
    features: ['Neo-brutalist style', 'Syne ExtraBold', 'Offset shadow frame', 'Date badge label'],
    isNew: true,
  },

  // ── Traditional ──────────────────────────────────────────────────────────
  {
    id: 'golden-paisley-017',
    name: 'Golden Paisley',
    description: 'Deep brown and gold with SVG paisley corner motifs and Devanagari mangalacharan. Rich Indian heritage.',
    category: 'traditional-indian',
    previewUrl: '/images/templates/golden-paisley.png',
    thumbnailUrl: '/images/templates/golden-paisley.png',
    tier: 'free',
    tags: ['paisley', 'gold', 'brown', 'devanagari', 'traditional'],
    features: ['Paisley motifs', 'Devanagari script', 'Gold gradient bands', 'Heritage palette'],
    isNew: true,
  },
  {
    id: 'marigold-fiesta-018',
    name: 'Marigold Fiesta',
    description: 'Saffron, maroon, and marigold with rangoli diamond strips and Yatra One Devanagari headers. Vibrant festival energy.',
    category: 'traditional-indian',
    previewUrl: '/images/templates/marigold-fiesta.png',
    thumbnailUrl: '/images/templates/marigold-fiesta.png',
    tier: 'free',
    tags: ['marigold', 'saffron', 'rangoli', 'maroon', 'festive'],
    features: ['Rangoli SVG strip', 'Chevron bands', 'Yatra One font', 'Festival colours'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'kerala-temple-019',
    name: 'Kerala Temple',
    description: 'Warm golden-saffron with SVG temple arch bands, mandala corner ornaments, and Noto Serif italic script.',
    category: 'traditional-indian',
    previewUrl: '/images/templates/kerala-temple.png',
    thumbnailUrl: '/images/templates/kerala-temple.png',
    tier: 'premium',
    tags: ['kerala', 'temple', 'mandala', 'south-indian', 'arch'],
    features: ['Temple arch bands', 'Mandala corners', 'Noto Serif', 'Saffron palette'],
    isNew: true,
  },
];


export const TEMPLATE_TIERS = {
  free: {
    label: 'Free',
    description: 'Watermarked downloads, shareable link',
    price: 0,
  },
  premium: {
    label: 'Premium',
    description: 'HD PNG, no watermark',
    price: 49,
  },
  'premium-plus': {
    label: 'Premium Plus',
    description: 'HD PNG, PDF, Envelope Design, no watermark',
    price: 99,
  },
};
